### PR TITLE
2.4.5.x Decadeus Update

### LINKED ISSUE #55: Detect invalid licence key on startup
Right now if the Main instance fails to be created due to an invalid licence key, the entrypoint will assume things went fine and will continue running even though no Main instance is ever created.

```
amp_1  | Making sure Main instance exists...
amp_1  | Creating Main instance... (This can take a while)
amp_1  | [Info] AMP Instance Manager v2.0.8.10 built 15/12/2020 17:10
amp_1  | [Info] Release spec: Release - built by CUBECODERS/buildbot on CCL-DEV
amp_1  | [Error] X is not a valid licence key.
```

We should detect the error and shut down the container.

### PR DESCRIPTION
**Pull request by MitchTalmadge**
- Updated Dockerfile and entrypoint scripts for new release process introduced with AMP 2.4.5.0
- Completely re-organized entrypoint into more maintainable functions
- Added improved error handling, especially when creating the main instance. Fixes #55 
- Removed old Java 16 -> 17 upgrade notice.
- Removed outdated "Check for Updates" GitHub Action.
  - I may go back on this -- still thinking about it.
  - With this, we will no longer be caching the latest AMP version inside the image itself. My goal was to make better use of the built-in update mechanisms in AMP to improve this container's longevity. The AMP upgrades will be downloaded on startup, unless the `AMP_AUTO_UPDATE` env var is set to `false`. 
  - To clarify: If you want to update AMP, just reboot the container. It happens automatically. No need to pull the image.
  - If `ampinstmgr` has an update, I will release a new image version after testing to make sure that it still works with our entrypoint. Based on `ampinstmgr`'s past, this will be infrequent.
- `LICENCE` is now `AMP_LICENCE`, `MODULE` is now `AMP_MODULE`, `NIGHTLY=true` is now `AMP_RELEASE_STREAM=Development`. 
  - Each of these are backwards compatible, old docker configs do not need to change.

### CODE REVIEW

**Comment by MitchTalmadge** [comment]
I upgraded a copy of my old 2.4.4.0 AMP server to 2.4.5 with this image, and it worked great. Have had no issues so far.

**Comment by IceOfWraith** [comment]
To get this to Ubuntu 22.04 all you need to do is the following three changes:

Line 1     - `FROM ubuntu:22.04`
Line 107 - `    lib32gcc-s1 \`
Line 161 - `RUN wget -qO - http://repo.cubecoders.com/archive.key | gpg --dearmor > /etc/apt/trusted.gpg.d/cubecoders-archive-keyring.gpg && \`

**Comment by IceOfWraith** [comment]
Very good! Didn't want to step on the changes you were working on here. :)

I'll let you know when I have the Wine/Xvfb changes ready and do a PR as well.

**Comment by MitchTalmadge** [comment]
I saw your PR #168! It looks awesome. I'm gonna merge this PR into `staging` since I haven't had any issues with it. Then we can test your additions and merge that in as well.

**Pull request merged**
